name: app_prefs
description: "Shared preferences with secure option"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: '>=9.2.4-0 <10.0.0'
  shared_preferences: '>=2.5.3-0'

dev_dependencies:
  flutter_lints: '>=5.0.0-0 <6.0.0'
  flutter_test:
    sdk: flutter
