name: app_id
description: "Store and generate unique app instance ID"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  app_prefs:
    path: ../app_prefs
  flutter:
    sdk: flutter
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: '>=5.0.0-0 <6.0.0'
  flutter_test:
    sdk: flutter
