name: auth_service
description: "Auth Service Package"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  app_prefs:
    path: ../app_prefs
  dartz: '>=0.10.1'
  equatable: '>=2.0.7-0 <3.0.0'
  flutter:
    sdk: flutter
  flutter_tools:
    git:
      url: git@github.com:Afflya/flutter_tools.git
      ref: master
  http: '>=1.3.0-0'
  jwt_decoder: '>=2.0.1-0 <3.0.0'

dev_dependencies:
  flutter_lints: '>=5.0.0-0 <6.0.0'
  flutter_test:
    sdk: flutter
