name: network_x
description: "Useful tools for network"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter
  http: '>=1.2.1'

dev_dependencies:
  flutter_lints: '>=5.0.0-0 <6.0.0'
  flutter_test:
    sdk: flutter
